hero-mob-finish
Anna23071986/project-Ukrainian_Clothes pull request #11
Opened 2023-10-29 18:47 UTC by ITAndrii

2023-10-29 21:25 UTC, Anna23071986 requested changes
пока все, дальше будет видно

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +<div class="container">
этот див должен быть внутри секции и оборачивать ее содержимое

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +    <div class="hero-link-container">
ордер это кнопка, а не див

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +      <a class="hero-link" href=""
в href поставь якорь на секцию #order

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +        ><p>Order</p>
p убрать, она не нужна, просто текст

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +          <use href="../img/hero-img/icon.svg#icon-arrow"></use>
лишнюю точку убери, оставь ./

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +      srcset="../img/hero-img/girl-1x.jpg 1x, ../img/hero-img/girl-2x.jpg 2x"
лишнюю точку убери, оставь ./

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +      src="../img/hero-img/girl-1x.jpg"
лишнюю точку убери, оставь ./

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +    <img
имг должен находиться в picture. добавь в него sourse для всех версий

2023-10-29 21:25 UTC, Anna23071986 commented on src/partials/hero.html
> +      width="335"
после добавления пикче ширину и высоту ставь максимальную из всех картинок. у тебя это 413, а высота 575

2023-10-29 21:25 UTC, Anna23071986 commented on src/css/hero.css
> +  letter-spacing: -0.01em;
по макету -4%, значит ставит -0,04em
и добавь letter-spacing

2023-10-29 21:38 UTC, ITAndrii commented on src/partials/hero.html
> +    <div class="hero-link-container">
ордер має бути реалізовано, як постлання а не кнопка. В ДЗ написано.

2023-10-29 21:39 UTC, ITAndrii commented on src/partials/hero.html
> +        ><p>Order</p>
Якщо реалізовувати посиланням, то р потрібен

2023-10-31 23:05 UTC, Anna23071986 requested changes
правки по мелочи. но самое главное ты забыл, я тебе говорила стрелочка на ссылке не как на макете, у нее другой размер

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +  padding-bottom: 40px;
я думаю тут правильнее будет поставить марджин, хотя могу ошибаться, готова обсудить

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +.elips-img {
я нигде не нашла у тебя этого класса, так что можно удалить

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    padding-top: 26px;
я думаю тут правильнее будет поставить марджин

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    line-height: 1.18;
если округлять, то правильнее 1,19

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +
добавь .hero-link { padding: 14px 39px; font-size: 16px; line-height: normal; letter-spacing: -0.64px;}
на таблете у кнопки поменялись значения

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    letter-spacing: -0.04em;
лайн-хейт нормал добавь

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    padding-top: 94px;
я думаю тут правильнее будет поставить марджин

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    right: 0px;
повторяется, убери

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    padding-top: 66px;
я думаю тут правильнее будет поставить марджин

2023-10-31 23:05 UTC, AnnaAkkerman commented on src/css/hero.css
> +    line-height: 1.16;
у тебя не указан letter-spacing. по макету он -1,92px.  уж не знаю все остальное, как на макете, но слово в заголовке переносится не так, как надо. либо подумай, как его правильно перенести, либо поставь значение -1.86рх. не по макету, но становится правильно, ну а потом будем с ментором разбираться

2023-10-31 23:05 UTC, Anna23071986 commented on src/partials/hero.html
> +          src="./img/hero-img/girl-mob-1x.jpg"
путь к таблет версии поставь, на ней картинка самая большая

2023-11-01 16:23 UTC, ITAndrii commented on src/css/hero.css
> +  padding-bottom: 40px;
Ставлю маржин, хоча також не впевнений

2023-11-01 16:25 UTC, ITAndrii commented on src/css/hero.css
> +.elips-img {
Забув, дякую.

2023-11-01 16:27 UTC, ITAndrii commented on src/css/hero.css
> +    padding-top: 26px;
+

2023-11-01 16:30 UTC, ITAndrii commented on src/css/hero.css
> +    line-height: 1.18;
+

2023-11-01 17:04 UTC, ITAndrii commented on src/css/hero.css
> +
+

2023-11-01 17:07 UTC, ITAndrii commented on src/css/hero.css
> +    padding-top: 94px;
+

2023-11-01 17:09 UTC, ITAndrii commented on src/css/hero.css
> +    right: 0px;
+

2023-11-01 17:10 UTC, ITAndrii commented on src/css/hero.css
> +    padding-top: 66px;
+

2023-11-01 17:20 UTC, ITAndrii commented on src/css/hero.css
> +    line-height: 1.16;
letter-spacing  по макету так і залишиться -0,03ем. Поставив -0,02ем.

2023-11-01 18:02 UTC, Anna23071986 approved these changes
молодец!

2023-11-01 18:02 UTC, merged