Collection
Anna23071986/project-Ukrainian_Clothes pull request #13
Opened 2023-10-30 01:07 UTC by MyroslavaRogoza

Пока что есть, остальное дальше буду фиксить. Баг с картинками 1280 знаю

2023-10-30 13:45 UTC, AnnaAkkerman requested changes
подчисть комменты и пустые классы. делай правки, а вопрос с точками я уже ментору написала

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/partials/collection.html
> +                        srcset="./img/collection-img/desc-1440-poltava-blouse.png 1x, ./img/collection-img/desc-1440-poltava-blouse@2x.png 2x"
я конечно могу ошибаться, но мне кажется, что картинки нужно было в jpeg формате качать, а не пнг

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/partials/collection.html
> +                        src="./img/collection-img/desc-1280-poltava-blouse.png"
тут нужно поставить картинку под размер 1440

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/partials/collection.html
> +                <h3 class="text-style collection-list-header">AUGUST Poltava women's blouseRING</h3>
сделай, как в остальных заголовках: с большой буквы, остальные маленькие

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/partials/collection.html
> +                        srcset="./img/collection-img/desc-1440-gorgany-blouse.png 1x, ../img/collection-img/desc-1440-gorgany-blouse@2x.png 2x"
точку лишнюю прибери ./

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/partials/collection.html
> +                        src="../img/collection-img/desc-1440-mountain-shirt.png"
точку лишнюю прибери ./

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +.collection-container{
фоновый рисунок добавь и добавь вертикальные паддинги

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/css/collection.css
> +    color: #FCF9F9;
есть в базовых стилях, убери

2023-10-30 13:45 UTC, AnnaAkkerman commented on src/css/collection.css
> +    line-height: 1.37;
по правилам округления 1,38

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +    color: #FCF9F9;
есть в базовых, убери

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +    font-style: normal;
значение по умолчанию, убери

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +.collection-list-item{
здесь не нужно задавать ширину, убери. в остальных версиях оставь

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +    padding-top: 18px;
по макету там расстояние между картинкой и контейнером, поэтому поменяй на марджин

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +        letter-spacing: -0.03em;
дублируешь, значение не поменялось, поэтому убери

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +            flex-basis: calc((100%-20*2)/3);
flex-basis: calc((100% - 40рх) / 3);

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +    @media screen and (max-width: 1439px) {
в версии (min-width: 768px) это уже есть, поэтому оно дублируется. Лучше и оттуда и отсюда убери и напиши в отдельном медиазапросе мин 768 энд макс1439

2023-10-30 13:45 UTC, Anna23071986 commented on src/css/collection.css
> +    @media screen and (min-width: 1400px){
дописать

2023-10-30 14:15 UTC, MyroslavaRogoza commented on src/partials/collection.html
> +                        srcset="./img/collection-img/desc-1440-poltava-blouse.png 1x, ./img/collection-img/desc-1440-poltava-blouse@2x.png 2x"
Ничего по этому поводу не сказано. Конвертировать в jpg?

2023-10-30 14:16 UTC, MyroslavaRogoza commented on src/css/collection.css
> +            flex-basis: calc((100%-20*2)/3);
Уже исправила

2023-10-31 13:57 UTC, Anna23071986 commented on src/partials/collection.html
> +                        srcset="./img/collection-img/desc-1440-poltava-blouse.png 1x, ./img/collection-img/desc-1440-poltava-blouse@2x.png 2x"
ну пока можешь не трогать, если ментор скажет, заменишь

2023-10-31 17:19 UTC, merged

2023-10-31 17:21 UTC, Anna23071986 commented
попробуй разве что приклеить орнамент к карточке. вроде как это background-attachment: fixed. поиграйся