Testimonials
Anna23071986/project-Ukrainian_Clothes pull request #4
Opened 2023-10-27 20:46 UTC by Mishyn-Kostiantyn

2023-10-28 12:31 UTC, Anna23071986 requested changes

2023-10-28 12:31 UTC, AnnaAkkerman commented on src/css/testimonials.css
> +.container {
Костя, давай так. Я посмотрела где-то половину, подход изначально неверный и одно тянет за собой другое. Я опишу сейчас самые главные моменты, дальше ты сам поймешь, потому что чуть ли не для каждой строки коммент нужен. 
1. .container вообще убери, в базовый стилях он уже есть, можешь зайти глянуть в base.css Твоя задача своему диву помимо этого класса дать дополнительный, в котором тебе останется прописать только вертикальные паддинги
2. медиазапрос делай не внутри стилей, а наоборот. Типа: 
@media screen and (min-width; 768px) { 
.testimonials-container { 
padding-right: 100px; padding-bottom: 100px; 
}
}
Также ширину контейнеру задавать не нужно, в базовых стилях уже есть нужные медиазапросы
3. В HTML picture убери, он там ни к чему, Картинка на все версиях одинаковая. Оставь просто img только srcset в него добавь
4. Ты отталкиваешься от десктопной версии в стилях. Нужно допустим:
 .section-tytle {
font-size: 32px;
font-weight; 500;
line-height; 1.38;
letter-spacing: -0.03em;
}
*/ font-style: normal уже есть по умолчанию
   color есть в базовых */
И только потом ты пишешь медиазапросы под планшетную и десктопную версию, где пишешь в них, что в .section-tytle поменялся font-size и line-height
6. Внеси пока эти правки, потому что из-за всего этого не могу распутать остальное

2023-10-28 23:25 UTC, Anna23071986 requested changes
До конца просмотреть так и не получилось. Проект должен быть выполнен про принципу ферст мобайл. У тебя базовые стили не для мобильной версии, а для десктопа, соответственно большинство медиазапросов теряют смысл

2023-10-28 23:25 UTC, Anna23071986 commented on src/partials/testimonials.html
> -                ../img/Testimonials/Maria-Tkachuk.jpg    1x,
на вебинаре говорили, что в пути лучше удалить вторую точку, после того, как задашь его   ./

2023-10-28 23:25 UTC, Anna23071986 commented on src/partials/testimonials.html
> -              width="64px"
в ширине и высоте должны быть цифры без пикселей

2023-10-28 23:25 UTC, Anna23071986 commented on src/css/testimonials.css
>    position: relative;
относительным лучше сделать li, в падинги добавь верхний. В макете нажми на card увидишь он там есть. Также в макете после основного заголовка отступ 40рх, поэтому верхний марджин здесь убери и добавь .section-title нижний марджин 40рх

2023-10-28 23:25 UTC, Anna23071986 commented on src/css/testimonials.css
> +    width: 335px;
лучше вместо width использовать flex-basis

2023-10-29 09:21 UTC, Mishyn-Kostiantyn commented on src/partials/testimonials.html
> -              width="64px"
Убрал

2023-10-29 09:24 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>    position: relative;
Сделал. Только нижний маржин у .section-title будет 64px - на макете 40рх до фото а оно у нас абсолют и не учитывается в размерах  самой li - так что чтобы было правильное расстояние добавил еще 24px

2023-10-29 09:24 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
> +    width: 335px;
Сделал

2023-10-29 09:26 UTC, Mishyn-Kostiantyn commented on src/partials/testimonials.html
> -                ../img/Testimonials/Maria-Tkachuk.jpg    1x,
Убрал

2023-10-29 12:43 UTC, AnnaAkkerman requested changes
костя очень прошу сделай по пунктам, тогда все получится. забыла отметить в html в img src  лишнюю точку убери

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
> +  padding: 80px 20px 80px 20px;
зря убрал padding-top: 80px. просто добавь еще нижний 80 и все. Боковые не нужны, они дублируются с базовыми

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
>    font-style: normal;
это не нужно, уже есть по умолчанию

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
>    line-height: 1.45;
забыл изменить. 44/32=1,38
а  letter-spacing мы вчера договорились со всеми писать в em То есть у тебя будет -0,03em

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
>    font-style: normal;
не нужно, есть по умолчанию

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
>    line-height: normal;
оставляй нормал только если у тебя в макете точно так стоит, потому что у меня стоит число в пикселях. хоть с нормалом вроде выглядит как нужно

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
>    letter-spacing: -0.15px;
в макете нет letter-spacing. Ни к чему, и без него выглядит правильно, особенно если добавить width с явно заданной шириной, то текст становится как надо. и не забудь добавить измененные размеры ширины в медиазапросы для каждой версии

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
> +  gap: 0px;
в мобильной версии гап не нужен, просто не пиши его. а в остальных версиях он останется

2023-10-29 12:43 UTC, AnnaAkkerman commented on src/css/testimonials.css
> +@media screen and (min-width: 768px) {
и добавь лайн хейт. в моб версии он 1,38 был а здесь 1,45

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
>      padding: 100px 32px 100px 32px;
только верхний и нижний по 100

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
> +    height: 286px;
не нужно высоту, если сделаешь правильно мои правки все становится как нужно

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
>      letter-spacing: -0.16px;
нет на макете и нет в нем нужды

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
>      padding: 150px 100px 150px 100px;
оставляешь только верхний и нижний

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
> +    height: 285px;
высоту убрать, не нужна.

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
> +    flex-basis: calc((100% - 26px) / 3);
calc((100% - 52px) / 3)
там 2 гапа по 26

2023-10-29 12:43 UTC, Anna23071986 commented on src/css/testimonials.css
>      height: 264px;
вообще не нужно

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>      height: 264px;
Убрал

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
> +    flex-basis: calc((100% - 26px) / 3);
Поправил

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
> +    height: 285px;
Убрал

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>      padding: 150px 100px 150px 100px;
поправил

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>      letter-spacing: -0.16px;
убрал

2023-10-29 15:32 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>    line-height: normal;
В макете так стоит

2023-10-29 15:33 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>    font-style: normal;
убрал

2023-10-29 15:33 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>    line-height: 1.45;
Поправил

2023-10-29 15:33 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
>    font-style: normal;
Убрал

2023-10-29 15:33 UTC, Mishyn-Kostiantyn commented on src/css/testimonials.css
> +  padding: 80px 20px 80px 20px;
Боковые убрал. Добавил нижний

2023-10-29 16:54 UTC, Anna23071986 commented on src/css/testimonials.css
>    line-height: normal;
ок

2023-10-29 17:14 UTC, Anna23071986 commented on src/css/testimonials.css
>      padding: 150px 100px 150px 100px;
нет, левый и правый остался в коде

2023-10-29 17:41 UTC, Anna23071986 approved these changes
молодец! мы это сделали!

2023-10-29 17:41 UTC, merged

2023-10-29 18:09 UTC, Mishyn-Kostiantyn commented
> молодец! мы это сделали!

Супер. Спасибо Тебе за рекомендации